name: Lint Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
#    container:
#      image: python:3.12-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install --upgrade pip setuptools && pip install --no-cache-dir poetry==2.1.3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libpq-dev make git -y && sudo apt-get clean && poetry config virtualenvs.create false && poetry install --no-root --no-interaction --no-ansi

      - name: Run lint-full-check
        run: git init && ls -la && make lint-full-check
