name: Lint Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install --upgrade pip setuptools && pip install --no-cache-dir poetry==2.1.3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libpq-dev -y && sudo apt-get clean && poetry config virtualenvs.create false && poetry install --no-root --no-interaction --no-ansi

      - name: Run lint-full-check
        run: make lint-full-check

  test:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_moviedb
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install --upgrade pip setuptools && pip install --no-cache-dir poetry==2.1.3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libpq-dev make git -y && sudo apt-get clean && poetry config virtualenvs.create false && poetry install --no-root --no-interaction --no-ansi

      - name: Run lint-full-check
        run: make test-with-coverage
